### ISSUE TITLE
Evaluation fails when the related samples collection is balanced.

### ISSUE THREAD

**Issue by nicolay-r** [nicolay-r/AREkit#21]

**Comment by nicolay-r** [comment]
The related exception:
```
Use standard file APIs to check for files with this prefix.
I1126 14:53:40.789392 140674235754304 saver.py:1280] Restoring parameters from output/ra-v2_0_large_neut_3l/cnn/cnn
I1126 14:53:40.912959 140674235754304 model.py:138] Minibatches passing per epoch count: ~1607 (Might be greater or equal, as the last bag is expanded)
I1126 14:53:40.913377 140674235754304 callback.py:122] 2020-11-26 14:53:40.913277: Epoch: 0: avg_fit_cost: -1.000, avg_fit_acc: -1.000
Predict e=0 [DataType.Train]: 1608it [00:23, 69.43it/s]                                                                 
Traceback (most recent call last):
  File "run_training.py", line 250, in <module>
    training_engine.run()
  File "/root/are-networks-experiments/arekit/common/experiment/engine/cv_based.py", line 35, in run
    self._handle_iteration(iter_index)
  File "/root/are-networks-experiments/arekit/contrib/networks/run_training.py", line 63, in _handle_iteration
    model.run_training(epochs_count=callback.Epochs)
  File "/root/are-networks-experiments/arekit/contrib/networks/core/model.py", line 121, in run_training
    self.fit(epochs_count=epochs_count)
  File "/root/are-networks-experiments/arekit/contrib/networks/core/model.py", line 145, in fit
    operation_cancel=operation_cancel)
  File "/root/are-networks-experiments/callback.py", line 138, in on_epoch_finished
    avg_fit_cost=avg_fit_cost)
  File "/root/are-networks-experiments/callback.py", line 165, in __test
    log_dir=self.__log_dir)
  File "/root/are-networks-experiments/arekit/contrib/networks/core/callback/utils_model_eval.py", line 50, in evaluate_model
    labels_formatter=RuSentRelLabelsFormatter())
  File "/root/are-networks-experiments/arekit/contrib/networks/core/callback/utils_model_eval.py", line 94, in perform_experiment_evaluation
    epoch_index=epoch_index)
  File "/root/are-networks-experiments/arekit/common/experiment/output/opinions/writer.py", line 13, in save_opinion_collections
    for doc_id, collection in opinion_collection_iter:
  File "/root/are-networks-experiments/arekit/common/experiment/output/opinions/converter.py", line 36, in iter_opinion_collections
    output.insert_news_ids_values(news_ids_values)
  File "/root/are-networks-experiments/arekit/common/experiment/output/base.py", line 33, in insert_news_ids_values
    self.__df.insert(1, const.NEWS_ID, news_ids_values)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2421, in insert
    value = self._sanitize_column(column, value, broadcast=False)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2568, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/series.py", line 2879, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
ValueError: Length of values does not match length of index
```
